### ISSUE TITLE
Code is not universal

### ISSUE THREAD

**Issue by muhammedeminakalan** [05akalan57/xfce_dynamic_wallpaper#2]
![image](https://user-images.githubusercontent.com/70916256/192075236-292da4fe-8deb-4360-a7eb-063b93522c55.png)

**Comment by juampe** [comment]
I made this script based on your code, as a fix to my environment
To summ up It can detect the workspaces and can be configured as Exec in the *.desktop file

xfce-dynamic-wallpaper.sh
```
#!/bin/bash

#This can be a problem if display is not the default
export DISPLAY=:0

#main loop
while true
do
        #Query about the workspaces
        WORKSPACES=$(xfconf-query -c xfce4-desktop -l -R | grep last-image)

        #For all workspaces in xfce ...
        for WORKSPACE in $WORKSPACES
        do
                #Get hour and use as dynamic bg
                HOUR=$(date '+%k')
                BACKGROUND="/opt/xfce-dynamic-wallpaper/backgrounds/$HOUR.jpg"
                xfconf-query -c xfce4-desktop -p "$WORKSPACE" -s "$BACKGROUND"
        done

        #Wait until o'clock
        WAITSECS=$(((60-$(date '+%_M'))*60))
        sleep $WAITSECS

done
```

**Comment by muhammedeminakalan** [comment]
Thank you for your contribution on Github. I am really pleased that the error was resolved gracefully. I will make the necessary adjustments immediately. Thank you again!

**Comment by juampe** [comment]
Thanks. I made a PR to avoid root, using shell, with user installation and a basic theme management
